function Line = LineSpec(LineNumber)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
LineTypes={'b-'...
    ,'g-.'...
    ,'r--'...
    ,'c:'...
    ,'b-*'...
    ,'g--o'...
    ,'r.-s'...
    ,'m:d'};
Line=LineTypes{LineNumber};
end

