function Line = LineSpec(LineNumber,LineType)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
switch LineType
    case 'line'
        LineTypes={'b-'...
            ,'g-.'...
            ,'r--'...
            ,'c:'...
            ,'b-*'...
            ,'g--o'...
            ,'r.-s'...
            ,'m:d'};
    case 'marker'
        LineTypes={'bo'...
            ,'g*.'...
            ,'rs'...
            ,'cd'...
            ,'bt'...
            ,'g--o'...
            ,'r.-s'...
            ,'m:d'};
end
Line=LineTypes{LineNumber};
end

